name: CLI Release

on:
  push:
    branches:
    - main
    paths:
    - 'dev-do-list-cli/**'
  workflow_dispatch:

jobs:
  release-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet cli
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Dotnet publish
        run: |
          dotnet restore;  
          dotnet publish -c Release;
        working-directory: dev-do-list-cli

      # Get PR from merged commit to master
      - name: Get merged pull request
        uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        id: draft_release
        with:
          publish: ${{ !contains(steps.get-merged-pull-request.outputs.labels, 'no-release') }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add release artifact
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: ./dev-do-list-cli/bin/Release/net8.0/**.exe
          asset_name: dev-do-list-cli.exe
          asset_content_type: application/octet-stream
    