name: 'Deploy Database Changes'

on:
  push:
    branches:
      - main
    paths:
      - Flyway/**
  
  workflow_dispatch:

env:
  SQLFLUFF_DIALECT: postgres
  DOCKER_IMAGE: redgate/flyway
  SCHEMAS: public

jobs:
  Continuous-Integration-Build:
    name: Continuous Integration Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1
          
      - name: Port forward Database
        run: |
          aws ssm start-session --target ${{ secrets.BASTION_HOST_ID }} --document-name AWS-StartPortForwardingSessionToRemoteHost --parameters '{"localPortNumber":["1433"],"portNumber":["1433"],"host":["${{ secrets.RDS_ENDPOINT }}"]}' --region eu-west-1 &

      - name: Build JDBC url
        run: |
          echo "DB_URL=jdbc:sqlserver://localhost:1433;authentication=sqlPassword;databaseName=DevDoListDB;encrypt=true;trustServerCertificate=true" >> $GITHUB_ENV

      - name: Continuous Integration Flyway Clean Migrate
        run: >-
          docker run --rm
          --net=host
          --volume ${{ github.workspace }}/Flyway/migrations:/flyway/sql:ro
          "${{ env.DOCKER_IMAGE }}"
          -url="${{ env.DB_URL }}"
          -user="${{ secrets.DB_USERNAME }}"
          -password="${{ secrets.DB_PASSWORD }}"
          info migrate
